#!/system/bin/sh
# 

busybox mount -o rw,remount /system
wget -q -O /cache/DroidSans.ttf http://dodgejcr.com/users/sdxtools/fonts/fonts_default/DroidSans.ttf
wget -q -O /cache/DroidSans-Bold.ttf http://dodgejcr.com/users/sdxtools/fonts/fonts_default/DroidSans-Bold.ttf
wget -q -O /cache/Clockopia.ttf http://dodgejcr.com/users/sdxtools/fonts/fonts_default/Clockopia.ttf
wget -q -O /cache/HelveticaNeueLTPro35Th.ttf http://dodgejcr.com/users/sdxtools/fonts/fonts_default/HelveticaNeueLTPro35Th.ttf
wget -q -O /cache/HelveticaNeueOTS.ttf http://dodgejcr.com/users/sdxtools/fonts/fonts_default/HelveticaNeueOTS.ttf
busybox mv -f /cache/HelveticaNeueLTPro35Th.ttf /system/fonts/HelveticaNeueLTPro35Th.ttf
busybox mv -f /cache/HelveticaNeueOTS.ttf /system/fonts/HelveticaNeueOTS.ttf
busybox mv -f /cache/DroidSans.ttf /system/fonts/DroidSans.ttf
busybox mv -f /cache/DroidSans-Bold.ttf /system/fonts/DroidSans-Bold.ttf
busybox mv -f /cache/Clockopia.ttf /system/fonts/Clockopia.ttf
busybox mount -o ro,remount /system
sync
pkill -f system_server
